### PR TITLE
add github corner to main site

### PR DESCRIPTION
**Pull request by maracuja-juice**
this adds a fork component to the site with the indicator color

### CODE REVIEW

**Comment by maracuja-juice** [comment]
@RohrerF I don't see how a snapshot test or anything like that will help. I will just merge this [after I pull down the new package version of github corner](https://github.com/skratchdot/react-github-corner/pull/47#issuecomment-381298567)

**Comment by RohrerF** [comment]
codecov won't be proud of you :)

**Comment by maracuja-juice** [comment]
Well then. So it is. -0.26% coverage is not so dramatic

**Comment by maracuja-juice** [comment]
@RohrerF Something is still wrong with the typings I added to their package. I think I forgot something...

**Pull request merged**
