### PR TITLE
WIP Refactoring to make things simpler

### PR DESCRIPTION
**Pull request by RohrerF**
TODO's:

- [x] activeboardReducer Action
- [x] fix smallboard not taking winning position
- [x] Fix Tests
- [x] place logic inside Sagas
- [x] clean up code
- [x] calculate winning player of the game
- [x] make Icons of SmallBoard big again
- [x] fix animation of icons
- [x] don't allow move after game is finished
- [x] fix material icon display...

### CODE REVIEW

**Comment by maracuja-juice** [comment]
package-lock.json should be excluded.

**Comment by maracuja-juice** [comment]
Looking quite good so far. 

In the getTiles Method of SmallBoard.tsx:
```
isClickable={isActive && tile.value !== TileValue.Empty}
```

shouldn't this be the following?
```
isClickable={isActive && tile.value === TileValue.Empty}
```

**Comment by RohrerF** [comment]
No, ```TileValue.Empty``` can't be the winner

**Comment by maracuja-juice** [comment]
If a tile is already used by a Player it shouldn't be clickable. What does this have to do with the winner? (only a small board can be won not a tile.)

**Comment by maracuja-juice** [comment]
Otherwise it looks good. In the render method of SmallBoard there are 1-2 opportunities to make the code clearer.

**Pull request merged**
