### PR TITLE
Add material restart button

### LINKED ISSUE #5: Add Restart Possibility
When the game ends a user should be able to restart the game.
Either via a button, click to restart or something else...

### PR DESCRIPTION
**Pull request by maracuja-juice**
At the end of the game the user should be able to restart the game via a button. This is made possible via this pull.
Closes #5 

For the material button I now use [rmwc](https://github.com/jamesmfriedman/rmwc). Material-UI and React-Toolbox didn't work well enough.

TODOs:
- [x] fix the saga tests/find out why they broke in the first place! 😮
- [x] improve responsiveness of button (on small screens it's way to big/doesn't align with the text. At least it should be under the text)
- [x] try out how it feels when I add an ease-out transition to the text/button (currently the disappearance of the button feels a bit weird/drastic), maybe also an ease-in transition
- [x] fix ease-out transition
- [x] fix game display tests (including tslint: line 57)
- [x] change color of button!
- [x] resolve conflicts with base branch 
- [x] add restart game tests to reducers

### CODE REVIEW

**Comment by maracuja-juice** [comment]
I added an ease-out transition (`transition: all 0.3s ease-out;`) but it changes to the default text before it is hidden. See this little demo:


Any suggestions @RohrerF? Should I just add a timeout or is there maybe an even better way?

**Comment by RohrerF** [comment]
I think a timeout is the easiest solution. Or you search for a better Solution than showing this `someText` thing

**Comment by maracuja-juice** [comment]
Not sure what you mean with a different solution. It would just be empty normally.
I'll try out how well the timeout works.

**Comment by maracuja-juice** [comment]
Now when I think a bit more about this I'm not really sure anymore where to put this timeout. Tried some places out but got some cool numbers in the text instead of what I wanted. 
I feel like a timeout is not the right way. (or I might be doing it completely wrong)

**Comment by maracuja-juice** [comment]
I now found a way to fix the issue with the transition. When the game is won I set the player that won to the state. And then when rendering the text I check if the game is currently won BUT the game was once won, in that case I'll render the text from the last won game.
Maybe there is a better/easier approach but this is the only one I got to work. (tried a few delay solutions)

**Comment by maracuja-juice** [comment]
Thanks for the nice refactoring session today @RohrerF

**Pull request merged**
